In [20]:
import numpy as np

a=np.arange(10) # prints numbers from 0 to 9
print(a)

b=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # an array of size 3 x 3
print(b)

c=np.random.rand(2, 2) # a random array of shape 2, 2
print(c)

d=np.arange(9).reshape(3, 3) #convert 1D array to 2D
print(d)

x=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y=np.array([[2, 3, 4], [5, 6, 7], [8, 9, 0]])
print(x+y) #element wise addition of two arrays

print(x*y) #element wise multiplication

print(np.dot(x, y)) #matrix multiplication

print(x.T) #transpose of matrix x

print(x+1) #element wise addition

#a basic ML calculation
p=np.array([[1, 2, 3], [4, 5, 6]]) #inputs
q=np.array([[0.1], [0.2], [0.3]]) #weights
print(np.dot(p, q)) #input x weights



[0 1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.78278446 0.23655318]
 [0.26017034 0.95830219]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 3  5  7]
 [ 9 11 13]
 [15 17  9]]
[[ 2  6 12]
 [20 30 42]
 [56 72  0]]
[[ 36  42  18]
 [ 81  96  51]
 [126 150  84]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
[[1.4]
 [3.2]]
